# Global env for steps
steps:
  # Terraform apply for deploy
  - id: 'terraform init'
    name: 'hashicorp/terraform:1.12.0'
    dir: terraform/deploy
    script: terraform init
  - id: 'terraform plan'
    name: 'hashicorp/terraform:1.12.0'
    dir: terraform/deploy
    script: terraform plan -out=tfplan
  - id: 'terraform apply'
    name: 'hashicorp/terraform:1.12.0'
    dir: terraform/deploy
    script: terraform apply tfplan
  # List revisions
  - id: 'list revisions'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - run
      - revisions
      - list
      - --region=$_REGION

  # script for traffic splits
  - id: 'traffic split'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - -c
      - |
        set -e
        SERVICE_NAME=$(gcloud run services list --region=$_REGION --format="value(metadata.name)" | head -n 1)
        REVISIONS=$(gcloud run revisions list --service=$SERVICE_NAME --region=$_REGION --format="value(metadata.name)")

options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'TF_VAR_project_id=$PROJECT_ID'
    - 'TF_VAR_region=$_REGION'

