steps:
    # Terraform apply for infra
  - name: 'hashicorp/terraform:light'
    entrypoint: 'bash'  
    args: ['-c', 'cd terraform/infra && terraform init && terraform apply -auto-approve']
    # Build the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME', '.']
    # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME']
    # Terraform apply for deploy
  - name: 'hashicorp/terraform:light'
    entrypoint: 'bash'
    args: ['-c', 'cd terraform/deploy &&terraform init && terraform apply -auto-approve']

options:
  logging: CLOUD_LOGGING_ONLY

# Deploy image to Cloud Run

# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   entrypoint: gcloud
#   args: ['run', 'deploy', 'SERVICE_NAME', '--image', 'LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE', '--region', 'SERVICE_REGION']
images:
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME'
