# Global env for steps
steps:
  # Terraform apply for deploy
  - id: 'terraform init'
    name: 'hashicorp/terraform:1.12.0'
    dir: terraform/deploy
    script: terraform init
  - id: 'terraform plan'
    name: 'hashicorp/terraform:1.12.0'
    dir: terraform/deploy
    script: terraform plan -out=tfplan
  - id: 'terraform apply'
    name: 'hashicorp/terraform:1.12.0'
    dir: terraform/deploy
    script: terraform apply tfplan
  # List revisions
  - id: 'list revisions'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - run
      - revisions
      - list
      - --region=$_REGION
      # Command for traffic with revisions 
options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'TF_VAR_project_id=$PROJECT_ID'
    - 'TF_VAR_region=$_REGION'
images:
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/$_IMAGE_NAME'
